require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  TargetRailsVersion: 4
  NewCops: enable

  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - vendor/**/*
    - log/**/*
    - config/initializers/pg_10.rb

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/graphql/**/*.rb
    - spec/**/*_spec.rb
    - spec/support/shared_examples/*.rb

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 20

Metrics/ModuleLength:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/Alias:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": ()
    "%w": ()

Style/SingleLineBlockParams:
  Enabled: false

# rspec
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
